name: wavemaker

channels:
  - defaults
  - conda-forge

dependencies:
  - python
  - jupyterlab
  - lightgbm
  - nbstripout
  - numpy
  - pandas
  - pip
  - plotnine
  - requests
  - scikit-learn=0.23.2  # higher versions have issues with skopt
  - scikit-optimize
  - seaborn
  - shap
  - tensorflow
  - tqdm

  - pip:
    - -e .
